actors:
  r7kamura:
    image_url: https://pbs.twimg.com/profile_images/790456968880062464/NWHT0Xn1_400x400.jpg
    name: r7kamura
    url: https://twitter.com/r7kamura
  9m:
    image_url: https://storage.kksg.net/images/9m.png
    name: 9m
    url: https://twitter.com/9m
  soramugi:
    image_url: https://pbs.twimg.com/profile_images/2863509226/5ebf54d483f89f1811fc0faa57acdcbe_400x400.jpeg
    name: soramugi
    url: https://twitter.com/soramugi
  itopoid:
    image_url: https://pbs.twimg.com/profile_images/660494969388449793/qL-fj-4e_400x400.png
    name: itopoid
    url: https://twitter.com/itopoid
android_podcast_subscription_url: http://subscribeonandroid.com/yatteiki.fm/feed.xml
author: やっていき手
description: 個人開発者達がやっていくPodcast
description_long: ものづくり、仕事、生活などをやっていく話題を中心に、いま現在やっている個人開発者達が話す、やっていき手のためのPodcast
email: soramugi.chika@gmail.com
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
hashtag: yatteikifm
itunes_podcast_url: https://itunes.apple.com/jp/podcast/yatteiki.fm/id1170904671?mt=2
keywords: tech,technology,yatteiki,programming,mobile,web,development,developer,software
language: ja
markdown: kramdown
permalink: /episode/:title
pushdog_subscription_url: https://push.dog/subscribe?url=https%3A%2F%2Fyatteiki.fm%2Ffeed.xml
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: yatteiki.fm
url: https://yatteiki.fm
