author: Yudai Tsuyuzaki
description: 個人開発者達がやっていくポッドキャスト
email: soramugi.chika@gmail.com
keywords: tech,technology,yatteiki,programming,mobile,web,development,developer,software
language: ja
markdown: kramdown
sass:
  sass_dir: css
title: yatteiki.fm
url: https://yatteikifm.github.io
exclude: ['Gemfile', 'Gemfile.lock', 'README.md', 'vendor/']
