author: やっていき手
description: 個人開発者達がやっていくポッドキャスト
email: soramugi.chika@gmail.com
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
keywords: tech,technology,yatteiki,programming,mobile,web,development,developer,software
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: yatteiki.fm
url: https://yatteikifm.github.io
